# Generated by Django 4.1.7 on 2023-04-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to='apiA.bus'),
        ),
    ]
